---
title: "git_01"
author: "Cristal Hernandez"
date: "Fall 2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Spring has arrived with joy,  
Welcomed by the birds with happy songs,  
And the brooks, amidst gentle breezes,  
Murmur sweetly as they flow. 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Twinkle, twinkle, little star,  
How I wonder what you are!  
Up above the world so high,  
Like a diamond in the sky.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
Loveliest of trees, the cherry now  
Is hung with bloom along the bough,  
And stands about the woodland ride  
Wearing white for Eastertide  

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
Her hands held me gently from the day I took my first breath.  
Her hands helped to guide me as I took my first step.  
Her hands held me close when the tears would start to fall.  
Her hands were quick to show me that she would take care of it all
